package com.pce_mason.qi.airpollution.AppClientHeader;

public interface ResultCode {
    //Result code
    int RESCODE_SAP_SGU_OK = 0,
        RESCODE_SAP_SGU_OTHER = 1,
        RESCODE_SAP_SGU_CONFLICT_OF_TEMPORARY_CLIENT_ID = 2,
        RESCODE_SAP_SGU_DUPLICATE_OF_USER_ID = 3;

    int RESCODE_SAP_SGI_OK = 0,
        RESCODE_SAP_SGI_OTHER = 1,
        RESCODE_SAP_SGI_CONFLICT_OF_TEMPORARY_CLIENT_ID = 2,
        RESCODE_SAP_SGI_NOT_EXIST_USER_ID = 3,
        RESCODE_SAP_SGI_INCORRECT_CURRENT_USER_PASSWORD = 4;

    int RESCODE_SAP_UVC_OK = 0,
        RESCODE_SAP_UVC_OTHER = 1,
        RESCODE_SAP_UVC_DUPLICATE_OF_USER_ID = 2,
        RESCODE_SAP_UVC_NOT_EXIT_A_TEMPORARY_CLIENT_IDDUPLICATE_OF_USER_ID = 3,
        RESCODE_SAP_UVC_INCORRECT_AUTHENTICATION_CODE = 4;

    int RESCODE_SAP_UPC_OK = 0,
        RESCODE_SAP_UPC_OTHER = 1,
        RESCODE_SAP_UPC_UNALLOCATED_USER_SEQUENCE_NUMBER = 2,
        RESCODE_SAP_UPC_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS = 3,
        RESCODE_SAP_UPC_INCORRECT_CURRENT_USER_PASSWORD = 4;

    int RESCODE_SAP_FPU_OK = 0,
        RESCODE_SAP_FPU_OTHER = 1,
        RESCODE_SAP_FPU_CONFLICT_OF_TEMPORARY_CLIENT_ID = 2,
        RESCODE_SAP_FPU_INCORRECT_USER_INFORMATION = 3,
        RESCODE_SAP_FPU_NOT_EXIST_USER_ID = 4;

    int RESCODE_SAP_SGO_OK = 0,
        RESCODE_SAP_SGO_OTHER = 1,
        RESCODE_SAP_SGO_UNALLOCATED_USER_SEQUENCE_NUMBER = 2,
        RESCODE_SAP_SGO_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS = 3;

    int RESCODE_SAP_SRG_OK = 0,
        RESCODE_SAP_SRG_OTHER = 1,
        RESCODE_SAP_SRG_UNALLOCATED_USER_SEQUENCE_NUMBER = 2,
        RESCODE_SAP_SRG_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS = 3;

    int RESCODE_SAP_SAS_OK = 0,
        RESCODE_SAP_SAS_OTHER = 1,
        RESCODE_SAP_SAS_UNALLOCATED_USER_SEQUENCE_NUMBER = 2,
        RESCODE_SAP_SAS_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS = 3,
        RESCODE_SAP_SAS_NOT_EXIST_WIFI_MAC_ADDRESS = 4,
        RESCODE_SAP_SAS_THE_REQUESTED_WIFI_MAC_ADDRESS_WAS_ALREADY_ASSOCIATED_WITH_USN = 5,
        RESCODE_SAP_SAS_THE_REQUESTED_WIFI_MAC_ADDRESS_WAS_ALREADY_ASSOCIATED_WITH_OTHER = 6;

    int RESCODE_SAP_SDD_OK = 0,
        RESCODE_SAP_SDD_OTHER = 1,
        RESCODE_SAP_SDD_UNALLOCATED_USER_SEQUENCE_NUMBER = 2,
        RESCODE_SAP_SDD_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS = 3,
        RESCODE_SAP_SDD_NOT_EXIST_WIFI_MAC_ADDRESS = 4,
        RESCODE_SAP_SDD_THE_REQUESTED_USER_SEQUENCE_NUMBER_AND_WIFI_MAC_ADDRESS_ARE_NOT_ASSOCIATED = 5;

    int RESCODE_SAP_SLV_OK = 0,
        RESCODE_SAP_SLV_OTHER = 1,
        RESCODE_SAP_SLV_UNALLOCATED_USER_SEQUENCE_NUMBER = 2,
        RESCODE_SAP_SLV_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS = 3;

    int RESCODE_SAP_DCA_OK = 0,
        RESCODE_SAP_DCA_OTHER = 1,
        RESCODE_SAP_DCA_UNALLOCATED_USER_SEQUENCE_NUMBER = 2,
        RESCODE_SAP_DCA_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS = 3;

    int RESCODE_SAP_DCD_OK = 0,
        RESCODE_SAP_DCD_OTHER = 1,
        RESCODE_SAP_DCD_UNALLOCATED_CONNECTION_ID = 2;

    int RESCODE_SAP_RAV_OK = 0,
        RESCODE_SAP_RAV_OTHER = 1,
        RESCODE_SAP_RAV_UNALLOCATED_USER_SEQUENCE_NUMBER = 2,
        RESCODE_SAP_RAV_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS = 3;

    int RESCODE_SAP_HHV_OK = 0,
        RESCODE_SAP_HHV_OTHER = 1,
        RESCODE_SAP_HHV_UNALLOCATED_USER_SEQUENCE_NUMBER = 2,
        RESCODE_SAP_HHV_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS = 3,
        RESCODE_SAP_HHV_UNAUTHORIZED_USER_SEQUENCE_NUMBER = 4;

    int RESCODE_SAP_KAS_OK = 0,
        RESCODE_SAP_KAS_OTHER = 1,
        RESCODE_SAP_KAS_UNALLOCATED_USER_SEQUENCE_NUMBER = 2,
        RESCODE_SAP_KAS_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS = 3;

}
